# -*- mode: ruby -*-
# vi: set ft=ruby :

IMAGE = 'matefarkas/xenial:base'

Vagrant.configure(2) do |config|
  config.vm.hostname = Dir.pwd.split('/')[-1]
  config.vm.provider "docker" do |docker|
    docker.image = IMAGE
  end
end
