# -*- mode: ruby -*-
# vi: set ft=ruby :

IMAGE = 'matefarkas/xenial:puppet5'

Vagrant.configure(2) do |config|
  config.vm.hostname = Dir.pwd.split('/')[-1]
  config.vm.provider "docker" do |docker|
    docker.image = IMAGE
    docker.has_ssh = true
  end
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
  config.ssh.forward_agent = true
  config.vm.provision "shell", path: "provision.sh"
end

