version: '3.5'

services:
  proxy:
    image: 'nginx:1.15.5-alpine'
    ports:
      - '80:80'
    volumes:
      - './proxy/index.html:/var/www/index.html:ro'
      - './proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro'

  apt:
    image: 'nginx:1.15.5-alpine'
    volumes:
      - './apt/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
      - './apt/repo/:/var/www/:ro'

