version: '3.5'

services:
  proxy:
    image: 'nginx:1.15.5-alpine'
    ports:
      - '80:80'
    volumes:
      - './proxy/index.html:/var/www/index.html:ro'
      - './proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro'

  apt:
    image: 'nginx:1.15.5-alpine'
    volumes:
      - './apt/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
      - './apt/repo/:/var/www/:ro'

  certbot:
    image: 'certbot/certbot:v0.27.1'
    volumes:
      - './certbot/letsencrypt/:/etc/letsencrypt/:rw' # RW
    command: 'renew --preferred-challenges=http --manual-auth-hook /etc/letsencrypt/renewal-hooks/manual/http-authenticator.sh --manual-cleanup-hook /etc/letsencrypt/renewal-hooks/manual/http-cleanup.sh'

